extends:
  - eslint:recommended
  - prettier
plugins:
  - prettier
parserOptions:
  ecmaVersion: 2017
env:
  node: true
  es6: true
rules:
  no-console: off
  prettier/prettier:
    - error
    -
      semi: false
      singleQuote: true
overrides:
  files: '**/*.test.js'
  env:
    jest: true
