extends:
  - eslint:recommended
  - standard
  - prettier
  - prettier/standard
plugins:
  - prettier
env:
  node: true
rules:
  no-console: off
  prettier/prettier:
    - error
    -
      semi: false
      singleQuote: true
overrides:
  files: '**/*.test.js'
  env:
    jest: true
